#import "@preview/min-book:1.4.0": themes

#let presets = (
  "blue-hexagon.jpg": (
    kind: "single",
    theme: themes.stylish,
    dy: 20%,
    dx: 0pt,
    width: 58%,
    title-fill: rgb("#f7efdb"),
    subtitle-fill: rgb("#e7d3a0"),
    meta-fill: rgb("#e4c47a"),
    heading-accent: rgb("#8f5b10"),
    heading-fill: rgb("#5b3006"),
    toc-title-fill: rgb("#3e2407"),
    toc-entry-fill: rgb("#4c3722"),
    toc-page-fill: rgb("#715530"),
    body-fill: rgb("#201a14"),
    styling: (reset: true),
    cover: (
      page: (fill: rgb("#1d2944")),
      title: (font: "Noto Serif", fill: rgb("#f2ead6")),
      text: (font: "Noto Serif", fill: rgb("#d7c49c")),
    ),
  ),
  "blue-jacket.jpg": (
    kind: "single",
    theme: themes.stylish,
    dy: 22%,
    dx: 0pt,
    width: 64%,
    title-fill: rgb("#f7f2e5"),
    subtitle-fill: rgb("#e2d2ae"),
    meta-fill: rgb("#dec188"),
    heading-accent: rgb("#8c6118"),
    heading-fill: rgb("#4f3010"),
    toc-title-fill: rgb("#35210c"),
    toc-entry-fill: rgb("#4e3923"),
    toc-page-fill: rgb("#705637"),
    body-fill: rgb("#201a14"),
    styling: (reset: true),
    cover: (
      page: (fill: rgb("#19344f")),
      title: (font: "Noto Serif", fill: rgb("#f5ecdb")),
      text: (font: "Noto Serif", fill: rgb("#d7c3a0")),
    ),
  ),
  "blue-lantern.jpg": (
    kind: "single",
    theme: themes.stylish,
    dy: 22%,
    dx: 0pt,
    width: 64%,
    title-fill: rgb("#f8f0df"),
    subtitle-fill: rgb("#e6d3af"),
    meta-fill: rgb("#e1c486"),
    heading-accent: rgb("#9b6913"),
    heading-fill: rgb("#5c3407"),
    toc-title-fill: rgb("#3a2206"),
    toc-entry-fill: rgb("#4f3923"),
    toc-page-fill: rgb("#72542d"),
    body-fill: rgb("#201a14"),
    styling: (reset: true),
    cover: (
      page: (fill: rgb("#1a3156")),
      title: (font: "Noto Serif", fill: rgb("#f3e7cf")),
      text: (font: "Noto Serif", fill: rgb("#dcc8a1")),
    ),
  ),
  "blue-plain.jpg": (
    kind: "single",
    theme: themes.stylish,
    dy: 20%,
    dx: 0pt,
    width: 58%,
    title-fill: rgb("#f7efdb"),
    subtitle-fill: rgb("#e7d3a0"),
    meta-fill: rgb("#e4c47a"),
    heading-accent: rgb("#7f5f1f"),
    heading-fill: rgb("#4d3611"),
    toc-title-fill: rgb("#38250c"),
    toc-entry-fill: rgb("#4a3824"),
    toc-page-fill: rgb("#6d5534"),
    body-fill: rgb("#201a14"),
    styling: (reset: true),
    cover: (
      page: (fill: rgb("#1e2570")),
      title: (font: "Noto Serif", fill: rgb("#f7efdc")),
      text: (font: "Noto Serif", fill: rgb("#ddc89a")),
    ),
  ),
  "book.jpg": (
    kind: "stacked",
    theme: themes.elegance,
    title-dy: 25%,
    subtitle-dy: 47%,
    meta-dy: 74%,
    width: 54%,
    title-fill: rgb("#f4e6bc"),
    subtitle-fill: rgb("#ebdcc0"),
    meta-fill: rgb("#f1dfaf"),
    heading-accent: rgb("#8a6822"),
    heading-fill: rgb("#3f3321"),
    toc-title-fill: rgb("#322618"),
    toc-entry-fill: rgb("#4a3c2a"),
    toc-page-fill: rgb("#7b6a4e"),
    body-fill: rgb("#241d15"),
    styling: (reset: true),
    cover: (
      text: (
        font: "Noto Serif",
        fill: rgb("#5f4d31"),
      ),
      page: (margin: 2cm),
    ),
  ),
  "brown-embross.jpg": (
    kind: "single",
    theme: themes.stylish,
    dy: 22%,
    dx: 0pt,
    width: 60%,
    title-fill: rgb("#f6e8ca"),
    subtitle-fill: rgb("#e7d5b0"),
    meta-fill: rgb("#ddc08a"),
    heading-accent: rgb("#8d6830"),
    heading-fill: rgb("#4d3113"),
    toc-title-fill: rgb("#332011"),
    toc-entry-fill: rgb("#4b3927"),
    toc-page-fill: rgb("#6d5338"),
    body-fill: rgb("#211915"),
    styling: (reset: true),
    cover: (
      page: (fill: rgb("#2a2726")),
      title: (font: "Noto Serif", fill: rgb("#f1e0c0")),
      text: (font: "Noto Serif", fill: rgb("#d8bc8e")),
    ),
  ),
  "brown-flowers.jpg": (
    kind: "single",
    theme: themes.elegance,
    dy: 24%,
    dx: 0pt,
    width: 62%,
    title-fill: rgb("#6b4218"),
    subtitle-fill: rgb("#7e5523"),
    meta-fill: rgb("#8b6733"),
    heading-accent: rgb("#a1732d"),
    heading-fill: rgb("#69431a"),
    toc-title-fill: rgb("#55351a"),
    toc-entry-fill: rgb("#6a5034"),
    toc-page-fill: rgb("#8f6d3a"),
    body-fill: rgb("#2f2217"),
    styling: (reset: true),
    cover: (
      text: (
        font: "Noto Serif",
        fill: rgb("#866129"),
      ),
      page: (margin: 2cm),
    ),
  ),
  "green-arc.jpg": (
    kind: "single",
    theme: themes.coffee,
    dy: 23%,
    dx: -6%,
    width: 60%,
    title-fill: rgb("#efe6c7"),
    subtitle-fill: rgb("#d8c89f"),
    meta-fill: rgb("#ccb47c"),
    heading-accent: rgb("#7a5d1f"),
    heading-fill: rgb("#284131"),
    toc-title-fill: rgb("#1e3328"),
    toc-entry-fill: rgb("#334a3e"),
    toc-page-fill: rgb("#7a6431"),
    body-fill: rgb("#1f2a24"),
    styling: (reset: true, flavor: "macchiato"),
    cover: (
      flavor: "macchiato",
      title: (font: "Noto Serif", fill: rgb("#efe3c0")),
      text: (font: "Noto Serif", fill: rgb("#d9c596")),
      page: (fill: rgb("#0f3229")),
    ),
  ),
  "green-stars.jpg": (
    kind: "single",
    theme: themes.stylish,
    dy: 23%,
    dx: 0pt,
    width: 62%,
    title-fill: rgb("#efe6c8"),
    subtitle-fill: rgb("#d8c7a0"),
    meta-fill: rgb("#cbb27c"),
    heading-accent: rgb("#8a6727"),
    heading-fill: rgb("#285446"),
    toc-title-fill: rgb("#203b31"),
    toc-entry-fill: rgb("#3e5b50"),
    toc-page-fill: rgb("#7c6842"),
    body-fill: rgb("#1e2b26"),
    styling: (reset: true),
    cover: (
      page: (fill: rgb("#0f5c68")),
      title: (font: "Noto Serif", fill: rgb("#efe3c6")),
      text: (font: "Noto Serif", fill: rgb("#d8c497")),
    ),
  ),
  "green.jpg": (
    kind: "single",
    theme: themes.elegance,
    dy: 24%,
    dx: 0pt,
    width: 60%,
    title-fill: rgb("#efe7ca"),
    subtitle-fill: rgb("#d9c9a3"),
    meta-fill: rgb("#ceb680"),
    heading-accent: rgb("#84703b"),
    heading-fill: rgb("#1e4a43"),
    toc-title-fill: rgb("#1a3430"),
    toc-entry-fill: rgb("#34504d"),
    toc-page-fill: rgb("#766844"),
    body-fill: rgb("#1d2b28"),
    styling: (reset: true),
    cover: (
      text: (
        font: "Noto Serif",
        fill: rgb("#58755d"),
      ),
      page: (margin: 2cm),
    ),
  ),
  "red-plain.jpg": (
    kind: "single",
    theme: themes.stylish,
    dy: 23%,
    dx: 0pt,
    width: 58%,
    title-fill: rgb("#f9f1df"),
    subtitle-fill: rgb("#ecd7b1"),
    meta-fill: rgb("#e5c78b"),
    heading-accent: rgb("#9d5b17"),
    heading-fill: rgb("#6b270f"),
    toc-title-fill: rgb("#4c1809"),
    toc-entry-fill: rgb("#66301e"),
    toc-page-fill: rgb("#84582f"),
    body-fill: rgb("#241915"),
    styling: (reset: true),
    cover: (
      page: (fill: rgb("#78111e")),
      title: (font: "Noto Serif", fill: rgb("#f7efdc")),
      text: (font: "Noto Serif", fill: rgb("#e0c490")),
    ),
  ),
  "white-flowers.jpg": (
    kind: "single",
    theme: themes.elegance,
    dy: 23%,
    dx: 0pt,
    width: 60%,
    title-fill: rgb("#6f451b"),
    subtitle-fill: rgb("#84592a"),
    meta-fill: rgb("#8f6c39"),
    heading-accent: rgb("#b07a2d"),
    heading-fill: rgb("#6e4a1f"),
    toc-title-fill: rgb("#57391a"),
    toc-entry-fill: rgb("#6b5132"),
    toc-page-fill: rgb("#8d6b37"),
    body-fill: rgb("#30251b"),
    styling: (reset: true),
    cover: (
      text: (
        font: "Noto Serif",
        fill: rgb("#8a642d"),
      ),
      page: (margin: 2cm),
    ),
  ),
  "white-plain.jpg": (
    kind: "single",
    theme: themes.elegance,
    dy: 23%,
    dx: 0pt,
    width: 58%,
    title-fill: rgb("#8a5823"),
    subtitle-fill: rgb("#9c6831"),
    meta-fill: rgb("#a77740"),
    heading-accent: rgb("#c07d32"),
    heading-fill: rgb("#7b4f1d"),
    toc-title-fill: rgb("#61401b"),
    toc-entry-fill: rgb("#735738"),
    toc-page-fill: rgb("#9d7540"),
    body-fill: rgb("#35281b"),
    styling: (reset: true),
    cover: (
      text: (
        font: "Noto Serif",
        fill: rgb("#9a6730"),
      ),
      page: (margin: 2cm),
    ),
  ),
  "white-roses.jpg": (
    kind: "single",
    theme: themes.elegance,
    dy: 23%,
    dx: 0pt,
    width: 60%,
    title-fill: rgb("#6f451b"),
    subtitle-fill: rgb("#84592a"),
    meta-fill: rgb("#8f6c39"),
    heading-accent: rgb("#ab7232"),
    heading-fill: rgb("#6f4820"),
    toc-title-fill: rgb("#57371b"),
    toc-entry-fill: rgb("#6d5132"),
    toc-page-fill: rgb("#8f6d3a"),
    body-fill: rgb("#30241a"),
    styling: (reset: true),
    cover: (
      text: (
        font: "Noto Serif",
        fill: rgb("#8b6130"),
      ),
      page: (margin: 2cm),
    ),
  ),
)

#let preset(name) = presets.at(name, default: presets.at("blue-hexagon.jpg"))
